version: 0.2
env:
  variables:
   parameter-store:
      Username: Arti_usr
      Pwd: Arti_pwd
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo installing maven...
      - sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
      - sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
      - sudo yum install -y apache-maven
  build:
    commands:
      - echo Build started on `date`
       - ls -ltr
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/main-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes
cache:
    paths:
    - '/root/.m2/**/*'
